### ISSUE TITLE
help Error

### ISSUE THREAD

**Issue by shortshows** [bulgakovk/steamBot#26]
C:\botarno>node bot2.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: InvalidPassword
    at SteamUser._handlers.(anonymous function) (C:\botarno\node_modules\steam-u
ser\components\logon.js:269:16)
    at SteamUser._handleMessage (C:\botarno\node_modules\steam-user\components\m
essages.js:165:29)
    at emitThree (events.js:97:13)
    at CMClient.emit (events.js:175:7)
    at CMClient._netMsgReceived (C:\botarno\node_modules\steam-user\node_modules
\steam-client\lib\cm_client.js:260:8)
    at CMClient.handlers.(anonymous function) (C:\botarno\node_modules\steam-use
r\node_modules\steam-client\lib\cm_client.js:358:8)
    at CMClient._netMsgReceived (C:\botarno\node_modules\steam-user\node_modules
\steam-client\lib\cm_client.js:242:24)
    at emitOne (events.js:77:13)
    at TCPConnection.emit (events.js:169:7)
    at TCPConnection._readPacket (C:\botarno\node_modules\steam-user\node_module
s\steam-client\lib\tcp_connection.js:59:7)

C:\botarno>pause
Press any key to continue . . .

**Comment by andrewda** [comment]
Steam like to throw InvalidPassword for a lot of stuff, including throttling login attempts and internal Steam issues/downtime. Try logging in again in a couple hours.
