### ISSUE TITLE
new help Error

### ISSUE THREAD

**Issue by shortshows** [bulgakovk/steamBot#28]
C:\botarno>node bot.js
Steam Guard App Code:
Steam Guard App Code: .......
Logged ON!
Got API key: ...........................................
C:\botarno\bot.js:99
                        newItems.forEach(function(newItem,i,arr){
                                ^

TypeError: Cannot read property 'forEach' of undefined
    at Request.callback [as _callback] (C:\botarno\bot.js:99:33)
    at Request.self.callback (C:\botarno\node_modules\request\request.js:198:22)

    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\botarno\node_modules\request\request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\botarno\node_modules\request\request.js:9
62:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

C:\botarno>pause
Press any key to continue . . .
this happens when it gets a trade

**Comment by andrewda** [comment]
I believe you edited the bot a little. Whatever edit(s) you made caused `newItems` to be `undefined` instead of an array.
